### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by JPSchellenberg** [Lumieducation/H5P-Nodejs-library#180] opened 2019-10-15 20:20 UTC
Hey,

I am not happy with the very big README. We should provide a `Quick Start` tutorial with our premade implementations (`FileContentStorage`, etc) in the README and move the detailed description somewhere else.  Maybe we should add a `docs/` and generate a [gitbook](https://www.gitbook.com) from the markdown files or use the wiki.

@sr258 what would you prefer?

**Comment by sr258** [comment] 2019-10-16 11:08
Duplicate of #166 I think. 

Yes, I think having Quick Start Tutorial in the README and putting the rest into a special documentation is a good idea.

I think as much of the documentation should be auto-generated (especially the interface documentation. If we have to update the documentation manually, I'm certain there will be inconsistencies btw. actual code and documentation)! Maybe having TS-interfaces with comments is enough documentation is some cases. I'm not familiar with GitBook but it looks good, so we can try it.

**Closed as completed** 2020-02-13 15:30 UTC
Labels: duplicate, enhancement, documentation
