### ISSUE TITLE
Missing translations from a fresh installation

### ISSUE THREAD

**Issue by vsilva472** [Lumieducation/H5P-Nodejs-library#732] opened 2020-08-18 01:07 UTC
**Describe the bug**
After a fresh install some package prints "Missing translations for library (...)" for buttons and labels

**Environment (please complete the following information):**
 - OS: Ubuntu 18.04
 - Browser: Chrome / Firefox (Both latest)
 - Nodejs-Version: 12.14.1

**To Reproduce**
1. Clone this repository
2. In a console `cd <PATH TO REPOSITORY>`
3. Run `npm install`
4. Run `npm run build` 
5. Point your browser to http://localhost:8080
6. Click on "Create New Content" button
7. From H5P hub select "Course Presentation" and click on "Get" button and then on "install" button and then on "use" button

**Expected behavior**
H5P Editor open with the correct strings and buttons
![image](https://user-images.githubusercontent.com/4265802/90458732-9626c300-e0d5-11ea-9851-2a1457e3e89c.png)

**Actual behavior**
H5P Editor open with the *Missing translations for library H5PEditor.CoursePresentation* and no buttons inside toolbar
![image](https://user-images.githubusercontent.com/4265802/90458881-fa498700-e0d5-11ea-8a9e-8df50e12f862.png)

**Additional context**
OS and Browsers are in EN language

**Comment by sr258** [comment] 2020-08-18 08:19
Thank you for your bug report. Can you check whether you browser is set to a locale like 'en-US' and not the generic 'en'? If so, this is probably a duplicate of #602

**Closed as completed** 2020-10-22 16:19 UTC
Labels: [type] bug, released
