### ISSUE TITLE
Postinstall-script does not run (cannot run in wd %s %s)

### ISSUE THREAD

**Issue by JPSchellenberg** [Lumieducation/H5P-Nodejs-library#18] opened 2019-06-05 09:43 UTC
Originally posted in #15 . The postinstall script fails and the H5P-scripts are not downloaded, which causes the Editor to not find the necessary scripts. 
It looks like the rights are not correct. [npm-issue](https://github.com/npm/npm/issues/19479)

One option could be to run `npm install --unsafe-perm` [stackoverflow](https://stackoverflow.com/questions/18136746/npm-install-failed-with-cannot-run-in-wd), but I would not want users to use the `--unsafe-perm`-flag.

![58878357-61e30480-86d3-11e9-9036-059745247462](https://user-images.githubusercontent.com/9697985/58946479-408f2080-8786-11e9-946d-19b0f95191c9.png)

Has anyone an idea?

**Comment by TheoGdrt** [comment] 2019-06-05 14:29
As said in Stackoverflow, add the flag in the package.json ? So users don't have to write it ?
`"config": {
    "unsafe-perm":true
}`

**Comment by JPSchellenberg** [comment] 2019-06-05 16:31
Can you test this, if it works? 
If it works you could make a pull request. ;)

**Comment by rtens** [comment] 2019-08-15 12:54
Could not reproduce this on Ubuntu and Windows 10.

Closing this issue since it seems out-dated. Please re-open if that's not the case.

**Closed as completed by rtens** 2019-08-15 12:54 UTC
Labels: [type] bug, help wanted, H5P-Editor, npm
